// This file will be auto-generated by Supabase CLI
// Run: npm run db:generate

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          name: string
          username: string
          avatar_url: string | null
          bio: string | null
          handicap: number | null
          rating_score: number
          stripe_account_id: string | null
          stripe_onboarding_complete: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['users']['Row'], 'id' | 'created_at' | 'rating_score'>
        Update: Partial<Database['public']['Tables']['users']['Insert']>
      }
      listings: {
        Row: {
          id: string
          seller_id: string
          title: string
          description: string
          brand: string
          category: string
          gender: string
          condition: string
          size: string
          price: number
          images: string[]
          status: string
          position_x: number | null
          position_y: number | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['listings']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['listings']['Insert']>
      }
      transactions: {
        Row: {
          id: string
          listing_id: string
          buyer_id: string
          seller_id: string
          amount: number
          platform_fee: number
          seller_payout: number
          stripe_payment_intent_id: string | null
          status: string
          tracking_number: string | null
          shipped_at: string | null
          delivered_at: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['transactions']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['transactions']['Insert']>
      }
      messages: {
        Row: {
          id: string
          transaction_id: string
          sender_id: string
          content: string
          read: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['messages']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['messages']['Insert']>
      }
    }
  }
}
